import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import { HomeVideo } from "./_app";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useEffect } from "react";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export default function Home() {
    const [seed, setSeed] = useState(1);
    const handleKeyPress = (event) => {
        if (event.code === "Space") {
            setSeed(Math.random());
        }
    };

    useEffect(() => {
        window.addEventListener("keydown", handleKeyPress);

        return () => window.removeEventListener("keydown", handleKeyPress);
    }, []);

    return (
        <>
            <Head>
                <title>Cofee visualizer</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/coffeevis_icon.svg" />
            </Head>
            <div
                className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
            >
                <main className={styles.main}>
                    <div className="row">
                        <div className="column-left">
                            <div className="video-bopping">
                                <HomeVideo key={seed}></HomeVideo>
                            </div>
                            <p>Press Space</p>
                        </div>
                        {/* <button onClick={reset}>Click me</button> */}
                        <div className="column-right">
                            <h1>A Quirky Music visualizer</h1>
                            <br></br>
                            <br></br>
                            <div className={styles.ctas}>
                                <a
                                    className={styles.primary}
                                    href="https://github.com/khoidauminh/coffeevis_rs?tab=readme-ov-file#installation"
                                    target="_blank"
                                    rel="noopener noreferrer"
                                >
                                    Install (version 0.5.1)
                                    <Image
                                        src="/linux_logo_icon_181333.png"
                                        alt="Linux logo"
                                        width={40}
                                        height={40}
                                    />
                                </a>
                            </div>
                        </div>
                    </div>
                </main>
                <footer className={styles.footer}>
                    <p>© 2021 - 2025, Cas Pascal</p>
                </footer>
            </div>
        </>
    );
}
